### ISSUE TITLE
--- In file name when imported from google drive

### ISSUE THREAD

**Issue by amgschnappi** [nextcloud/integration_google#175]
### Which version of integration_google are you using?

Latest

### Which version of Nextcloud are you using?

Latest

### Describe the Bug

1. Install nc 
2. Install google integration
3. Give client id and secret
4. Data migrate

File name has only ----
Not the actual file name

![Screenshot 2024-08-07 230144](https://github.com/user-attachments/assets/64200d10-0c11-4ece-ba8e-7a9a2bfa69e1)

### Expected Behavior

Actual filename from google drive should be shown

### To Reproduce

Prereq: Docker compose as below
```
name: nextcloud
services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8088:80
    volumes:
      - ..\NextCloud\data:/var/www/html/data
    environment:
      OVERWRITEPROTOCOL: https
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
    restart: always
    volumes:
      - ..\NextCloud\db_data:/var/lib/postgresql/data
    expose:
      - 5432

```

1. Install nextcloud on win11 with docker desktop using following batch file :  

```
cd %UserProfile%\Documents\Docker\NextCloud

docker compose stop
docker compose pull
docker compose up -d --remove-orphans

timeout /t 999

 call docker exec --user www-data -it nextcloud-app-1 php occ config:system:get trusted_domains
 call docker exec --user www-data nextcloud-app-1 php /var/www/html/cron.php
 call docker exec --user www-data -it nextcloud-app-1 php occ config:system:set maintenance_window_start --type=integer --value=100
 call docker exec --user www-data -it nextcloud-app-1 php occ db:add-missing-indices
 call docker exec --user www-data -it nextcloud-app-1 php occ app:install richdocumentscode
 call docker exec --user www-data -it nextcloud-app-1 php occ app:install richdocuments
 call docker exec --user www-data -it nextcloud-app-1 php occ app:install memories
 call docker exec --user www-data -it nextcloud-app-1 php occ app:install recognize
 call docker exec --user www-data -it nextcloud-app-1 php occ recognize:download-models
 call docker exec --user www-data -it nextcloud-app-1 php occ app:install integration_google
```

2. Create and login with admin
3. Enter client id and client secret in connected accounts menu of setting
4. Use data migration menu to import all the google drive files
